name: rx_state_machine_example
description: An example project for the rx_state_machine.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rx_state_machine:
    path: ../

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0