name: rx_state_machine
description: >-
  A library for finite state machine realization in Dart similar to the [Tinder StateMachine library](https://github.com/Tinder/StateMachine).
version: 1.0.2
homepage: https://github.com/mi-sch-ka
repository: https://github.com/mi-sch-ka/rx-state-machine
issue_tracker: https://github.com/mi-sch-ka/rx-state-machine/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # reactive programming: additional capabilities to dart streams and stream-controllers.
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.0

flutter:
  uses-material-design: false